trigger:
- master
pool:
  vmImage: Default
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'Angular CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install @angular/cli'
- task: Npm@1
  displayName: Build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'ng test'
  inputs:
    verbose: false
    customCommand: 'run test'

- task: ArchiveFiles@2
  displayName: 'Archive FIles'
  inputs:
    rootFolderOrFile: dist
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)/a'
    artifact: drop
- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App : to-do-list-frontend'
  inputs:
    azureSubscription: 'c996ad2b-c26d-4f31-a4c1-3fbbbf1d96ca'
    appName: 'to-do-list-frontend'
    appType: webApp
    package: $(Pipeline.Workspace)/**/*.zip