trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Angular CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli'


    customCommand: 'install @angular/cli'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    customCommand: 'install'

- task: Npm@1
  displayName: 'install dev'
  inputs:
    verbose: false
    customCommand: 'install --only=dev'


- task: Npm@1
  displayName: 'Build On'
  displayName: Build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'tests' 
  displayName: 'ng test'
  inputs:
    command: custom
    customCommand: ng test
    verbose: false

- task: ArchiveFiles@2